### PR TITLE
Stores global lockdrop stats and serves them instead of using INFURA

### PR DESCRIPTION
**Pull request by drewstone**
## Description

Adds an `UPDATE_EDGEWARE_LOCKDROP_STATS` flag to once and for all store all global statistics from the lockdrop. This will need to be run once on prod and then we can remove our dependence on INFURA for these statistics since we would need archival support.

Uses the stored statistics to server the lockdrop stats page instead of continuous polling.

## Motivation and Context

We want the lockdrop stats up and working without needing to keep paying for INFURA archive support.

## How Has This Been Tested?

Running the lockdrop routes and pages after running the update stats script (`yarn update-edgeware-lockdrop`)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have linted the code locally prior to submission.

### CODE REVIEW

**Comment by raykyri** [comment]
What still needs resolving on this branch?

**Comment by drewstone** [comment]
Ok so after running `yarn update-edgeware-lockdrop` on prod we will populate the DB with the entirety of lockdrop stats. This way we won't need to keep paying for archive support for global and individual stats.

@raykyri lmk your thoughts.

**Comment by raykyri** [comment]
Does `UPDATE_EDGEWARE_LOCKDROP_STATS=true ts-node --project tsconfig.node.json server.ts` print any output? It appears to be freezing up for me.

**Comment by drewstone** [comment]
Do you have the INFURA key set? @raykyri

**Comment by drewstone** [comment]
@raykyri I'm not having issues running this locally, it does take time to run. I would need more info on why its not working on prod if you can share.

**Pull request merged**
