### PR TITLE
Emit events for chain notifications (re-posted after revert)

### PR DESCRIPTION
**Pull request by drewstone**
## Description
This PR tracks the progress of the "chain notifications" project. The intent is to fetch events from various chains, process them on the server, possibly storing them in the database, and emit them as notifications to the end user.

## Motivation and Context
We already have a notification system in place, but it currently provides notifications for discussion events only. We would like to expand its scope and notify users about other important events taking place on chains they're interested in.

## How Has This Been Tested?
Unit test cases and running it with a local edgeware chain.

## TODO for MVP
- [x] Remove `manage_chain_notifications_modal` and add subscription types to the /subscriptions page.
- [x] Add proper formatting for displaying balances within notifications.
- [x] (is this possible?) Ensure that proposal event creators don't receive a notification immediately upon creation.
- [ ] ~Add webhook data.~
  - **Separate PR**.
- [x] @raykyri Ensure interface of notification pulldown is correct -- I moved some buttons around, we should confirm their positioning.
- [x] @raykyri Verify that url-linking when clicking on a notification is working as intended in all cases (e.g. if the proposal page no longer exists, or if we have no link available).
- [x] @raykyri Verify subscriptions page looks OK.

## Types of changes
- [x] New feature (non-breaking change which adds functionality)

## Checklist:
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] My change should be included in the release notes.
- [x] I have updated the documentation accordingly.
- [ ] I have linted the code locally prior to submission.

### CODE REVIEW

**Comment by dillchen** [comment]
@jnaviask great work.

A few small changes in this specific PR before merging.
- It's a little confusing that we populate notifications where we don't have pages for (this should resolve over time as we build out those pages). For example, can't click into a notification for a preimage or validator reward.

Things to add on this PR 
- [ ] Currently isn't a council candidacy event. I.e "jake-edg has submitted their council candidacy", which would take us to the council page.
- [ ] In the notification `heading`, we should add the chain's name: I.e "Democracy Proposal Created" would now be “Democracy Proposal Created on [chain.name]”. I would imagine can cause a bit of confusion once we have events across multiple chains / projects flowing.

I have a few notes on changes to the Subscriptions / Notifications Page but think this can be addressed separately next week by @zakhap and I.

**Comment by jnaviask** [comment]
Agreed re links, archiving will be a big help on this one though. The council change will take a bit of work but hopefully I can get it all in tomorrow. Title change should be easy.

**Comment by jnaviask** [comment]
Also need to do a merge tomorrow with master to fix the branch, looks like.

**Comment by raykyri** [comment]
Finally got around to looking at this (sorry for the delay). Looks good! I think the subscription page makes sense, and should not be hard to work with to turn into something easy to use later this month.

**Pull request merged**
